name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Define secrets
      env: 
        NOT_SO_SECRET: ${{ secrets.NOT_SO_SECRET }}
        ANOTHER_NOT_SO_SECRET: ${{ secrets.ANOTHER_NOT_SO_SECRET }}
    - name: Print secrets
      run: |
        echo "${{ env.NOT_SO_SECRET }}"
        echo "${{ env.ANOTHER_NOT_SO_SECRET }}"

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}
    # - name: List S3 Buckets
    #   run: aws s3api list-buckets
